package br.com.rspinfotec.shared

const val INPUT_DIR = "data/download"
const val OUTPUT_DIR = "data/output"
const val PREFIX_CNAE = "Cnaes"
const val PREFIX_EMPRESA = "Empresas"
const val PREFIX_ESTABELECIMENTO = "Estabelecimentos"
const val PREFIX_SOCIOS = "Socios"
const val PREFIX_PAIS = "Paises"
const val PREFIX_QUALIFICACOES = "Qualificacoes"
const val PREFIX_SIMPLES = "Simples"
const val TIPO_ARQUIVO_ACEITO = "zip+csv"
const val PREFIX_MUNICIPIOS = "Municipios"
const val PREFIX_NATUREZA_JURIDICA = "Naturezas"
const val PREFIX_MOTIVOS = "Motivos"

const val TABLE_SOCIOS = "socios"
const val TABLE_ESTABELECIMENTOS  = "estabelecimentos"
const val TABLE_SIMPLES = "simples"
const val TABLE_EMPRESAS = "empresas"
const val TABLE_CNAE = "cnaes"
const val TABLE_PAISES = "paises"
const val TABLE_QUALIFICACAO_SOCIO = "qualificacoes_socios"
const val TABLE_MUNICIPIOS = "municipios"
const val TABLE_NATUREZAS_JURIDICAS = "naturezas_juridicas"
const val TABLE_MOTIVO_SITUACAO_CADASTRAL = "motivo_situacao_cadastral"