micronaut:
  jcache:
    enabled: False
  server:
    port: ${API_PORT}
  application:
    name: receita
  serde:
    serialization:
      inclusion: NON_ABSENT
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 200
        hbm2ddl:
          auto: none
        connection:
          db-type: postgres
          url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
          username: ${DB_USER}
          password: ${DB_PASSWORD}
    reactive: true
db:
  uri: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
